#!name=Ads include
#!desc=Ads include

[Rule]
DOMAIN-SET,https://anti-ad.net/surge2.txt,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/elnfnoosm/iOS_network/main/rule/Reject-rule/Reject-rule.list,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/elnfnoosm/iOS_network/main/rule/China-rule/China-rule.list,REJECT
# > Chan QC HDOBOX
DOMAIN-SUFFIX,applovin.com,REJECT
DOMAIN-SUFFIX,applvn.com,REJECT
