#!name=Ads include
#!desc=Ads include

[Rule]
URL-REGEX,^https?:\/\/tiktok.com\/whale\/,REJECT-TINYGIF
URL-REGEX,^https?:\/\/tiktok.com\/web\/report\?,REJECT-TINYGIF
URL-REGEX,^https?:\/\/tiktok.com\/v1\/list,REJECT-TINYGIF
URL-REGEX,^https?:\/\/tiktok.com\/captcha\/report,REJECT-TINYGIF
DOMAIN-SUFFIX,analytics.tiktok.com,REJECT
DOMAIN-SUFFIX,analytics-sg.tiktok.com,REJECT
DOMAIN-SUFFIX,v45.tiktokcdn.com,REJECT
DOMAIN-SUFFIX,ttoverseaus.net,REJECT
DOMAIN-SUFFIX,ecdnx.com,REJECT
DOMAIN-SUFFIX,switserve.com,REJECT
DOMAIN-SUFFIX,fastly.net,REJECT
DOMAIN-SUFFIX,firebaselogging-pa.googleapis.com,REJECT
DOMAIN-SUFFIX,atomile.com,REJECT
DOMAIN-SUFFIX,bytetcdn.com,REJECT
DOMAIN-SUFFIX,iadsdk.apple.com,REJECT
DOMAIN-SUFFIX,worldfcdn.com,REJECT
DOMAIN-SUFFIX,wsdvs.com,REJECT
DOMAIN-SUFFIX,queniuaa.com,REJECT
DOMAIN-SUFFIX,myqcloud.com,REJECT
DOMAIN-SUFFIX,byteoversea.net,REJECT
DOMAIN-SUFFIX,bytecdn-oversea.com,REJECT
DOMAIN-SUFFIX,snapchat.com,REJECT
DOMAIN-SUFFIX,rocket-cdn.com,REJECT
DOMAIN-SUFFIX,cdn77.org,REJECT
DOMAIN-SUFFIX,akamai.net,REJECT
DOMAIN-SUFFIX,akamai.com,REJECT
DOMAIN-SUFFIX,akamaiedge.net,REJECT
DOMAIN-SUFFIX,akadns.net,REJECT
DOMAIN-SUFFIX,apple-dns.net,REJECT
DOMAIN-SUFFIX,c10r.facebook.com,REJECT
DOMAIN-SUFFIX,m.facebook.com,REJECT
DOMAIN-SUFFIX,content.xx.fbcdn.net,REJECT
# > HDOBOX 去广告
DOMAIN-SUFFIX,applovin.com,REJECT
DOMAIN-SUFFIX,applvn.com,REJECT

[URL Rewrite]
#^https?:\/\/api\d?\.tiktokv\.com\/api\/ad\/ _ REJECT
#^https?:\/\/api\d?\.musical\.ly\/api\/ad\/ _ REJECT
#^https?:\/\/.+?\.(musical|snssdk|tiktokv)\.(com|ly)\/(api|motor)\/ad\/ _ REJECT
#^https?:\/\/.+?\.(musical|snssdk)\.(com|ly)\/(api|motor)\/ad\/ _ REJECT
#^https?:\/\/.+?\.(snssdk|amemv)\.com\/api\/ad\/ _ REJECT
#^https?:\/\/aweme\.snssdk\.com\/aweme\/v1\/aweme\/stats\/ _ REJECT
#^https?:\/\/aweme\.snssdk\.com\/aweme\/v1\/device\/update\/ _ REJECT
#^https?:\/\/aweme\.snssdk\.com\/aweme\/v1\/screen\/ad\/ _ REJECT
#^https?:\/\/aweme\.snssdk\.com\/service\/1\/app_logout\/ _ REJECT
#^https?:\/\/aweme\.snssdk\.com\/service\/2\/app_log _ REJECT
#^https?:\/\/frontier\.snssdk\.com\/ - reject
#^https?:\/\/.+?\.(musical|snssdk)\.(com|ly)\/(api|motor)\/ad\/ _ REJECT
#^https?:\/\/.+?\.snssdk\.com\/motor\/operation\/activity\/display\/config\/V2\/ _ REJECT
#^https?:\/\/[\s\S]*\.snssdk\.com\/api\/ad\/ _ REJECT
#^https?:\/\/connect\.facebook\.net\/en_US\/fbadnw\.js _ REJECT

[MITM]
hostname = %APPEND% api*.tiktokv.com, *.musical.ly, *.byteoversea.com, lf.snssdk.com, *.snssdk.com, connect.facebook.net, www.facebook.com
