#!name=Ads include
#!desc=Ads include

[Rule]
URL-REGEX,^https?:\/\/api\d?\.tiktokv\.com\/api\/ad\/,REJECT-TINYGIF
URL-REGEX,^https?:\/\/api\d?\.musical\.ly\/api\/ad\/,REJECT-TINYGIF
URL-REGEX,^https?:\/\/.+?\.(musical|snssdk|tiktokv)\.(com|ly)\/(api|motor)\/ad\/,REJECT-TINYGIF
URL-REGEX,^https?:\/\/connect\.facebook\.net\/en_US\/fbadnw\.js,REJECT-TINYGIF
DOMAIN-SUFFIX,mcs-va.tiktok.com,REJECT
DOMAIN-SUFFIX,ibytedtos.com,REJECT
DOMAIN-SUFFIX,analytics-sg.tiktok.com,REJECT
DOMAIN-SUFFIX,analytics.tiktok.com,REJECT
DOMAIN-SUFFIX,v45.tiktokcdn.com,REJECT
DOMAIN-SUFFIX,ttoverseaus.net,REJECT
DOMAIN-SUFFIX,ecdnx.com,REJECT
DOMAIN-SUFFIX,switserve.com,REJECT
DOMAIN-SUFFIX,fastly.net,REJECT
DOMAIN-SUFFIX,firebaselogging-pa.googleapis.com,REJECT
DOMAIN-SUFFIX,atomile.com,REJECT
DOMAIN-SUFFIX,bytetcdn.com,REJECT
DOMAIN-SUFFIX,iadsdk.apple.com,REJECT
DOMAIN-SUFFIX,worldfcdn.com,REJECT
DOMAIN-SUFFIX,wsdvs.com,REJECT
DOMAIN-SUFFIX,queniuaa.com,REJECT
DOMAIN-SUFFIX,myqcloud.com,REJECT
DOMAIN-KEYWORD,byteoversea.net,REJECT
DOMAIN-KEYWORD,bytecdn-oversea.com,REJECT
DOMAIN-SUFFIX,snapchat.com,REJECT
DOMAIN-SUFFIX,rocket-cdn.com,REJECT
DOMAIN-SUFFIX,cdn77.org,REJECT
DOMAIN-KEYWORD,akamai.net,REJECT
DOMAIN-KEYWORD,akamai.com,REJECT
DOMAIN-KEYWORD,akamaiedge.net,REJECT
DOMAIN-KEYWORD,akadns.net,REJECT
DOMAIN-SUFFIX,apple-dns.net,REJECT
DOMAIN-SUFFIX,c10r.facebook.com,REJECT
DOMAIN-SUFFIX,m.facebook.com,REJECT
DOMAIN-SUFFIX,content.xx.fbcdn.net,REJECT
# > Chan QC HDOBOX
DOMAIN-SUFFIX,applovin.com,REJECT
DOMAIN-SUFFIX,applvn.com,REJECT

[MITM]
hostname = %APPEND% *.tiktokv.com, *.byteoversea.com, connect.facebook.net, www.facebook.com, *.musical.ly
