#!name=Unlock Spotify
#!desc=Partial unlocking Premium

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
Spotify-Premium = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/luxysiv/scripts/main/spotify-proto.js,script-update-interval=0
